"""``hermes keypair`` subcommand parser."""

from __future__ import annotations

from typing import Callable


def build_keypair_parser(subparsers, *, cmd_keypair: Callable) -> None:
    """Attach the ``keypair`` subcommand to ``subparsers``."""
    keypair_parser = subparsers.add_parser(
        "keypair", help="Sign with this profile's Ed25519 key or print its public key",
        description=(
            "Each profile has an Ed25519 keypair, generated by its gateway at startup. "
            "The private key never leaves the profile: this command signs with it and "
            "prints the public half."
        ),
    )
    keypair_sub = keypair_parser.add_subparsers(dest="keypair_action")
    keypair_sub.add_parser("show", help="Print the public key (PEM)")
    sign_parser = keypair_sub.add_parser("sign", help="Print a base64 Ed25519 signature of a file or stdin")
    sign_parser.add_argument("file", nargs="?", default="-", help="File to sign (default: stdin)")
    keypair_parser.set_defaults(func=cmd_keypair)
